In [4]:
import numpy as np
import pandas as pd

In [14]:
#1

rolls = np.random.choice(range(1,7),size=(10000,2))
rolls

array([[5, 4],
       [1, 3],
       [1, 1],
       ...,
       [6, 6],
       [6, 2],
       [6, 2]])

In [21]:
total=0
for i in range(1,7):
    total += (rolls == i).all(axis=1).mean()
total

0.1664

In [16]:
#2

flips = np.random.choice(['Heads','Tails'],(10000,8))
flips

array([['Tails', 'Tails', 'Tails', ..., 'Tails', 'Heads', 'Tails'],
       ['Tails', 'Tails', 'Tails', ..., 'Heads', 'Tails', 'Heads'],
       ['Tails', 'Tails', 'Heads', ..., 'Tails', 'Heads', 'Heads'],
       ...,
       ['Heads', 'Heads', 'Tails', ..., 'Heads', 'Heads', 'Tails'],
       ['Heads', 'Heads', 'Heads', ..., 'Heads', 'Heads', 'Heads'],
       ['Tails', 'Heads', 'Tails', ..., 'Tails', 'Heads', 'Tails']],
      dtype='<U5')

In [20]:
((flips == 'Heads').sum(axis=1) == 3).mean()

0.2133

In [29]:
((flips == 'Heads').sum(axis=1) > 3).mean()

0.6444

In [36]:
#3

boards = np.random.choice(['DS','WD'],p=(1/4, 3/4), size=(10000, 2))
boards

array([['WD', 'DS'],
       ['DS', 'WD'],
       ['DS', 'WD'],
       ...,
       ['WD', 'WD'],
       ['WD', 'WD'],
       ['WD', 'WD']], dtype='<U2')

In [37]:
((boards == 'DS').all(axis=1) == True).mean()

0.0681

In [28]:
#4

poptarts = np.random.normal(3,1.5, size=(10000,5))
poptarts

array([[ 0.42609086, -0.28579014,  5.82358537,  0.75204469,  1.48475562],
       [ 3.82194174,  3.00640487,  3.90339914,  2.22629575,  2.6068994 ],
       [ 3.68074061,  0.84418623,  1.74136287,  4.34791118,  1.31495002],
       ...,
       [ 1.31023068,  5.6546251 ,  3.89792147,  5.4058145 ,  3.36320691],
       [ 6.48304356,  2.12418442,  4.48301282,  4.46748095,  3.13385681],
       [-1.02803093,  2.4857882 ,  3.45911244,  3.31092548,  3.97873353]])

In [38]:
(poptarts.sum(axis=1) <= 16).mean()

0.6094

In [62]:
#5

m_height = np.random.normal(178, 8, size=10000)
f_height = np.random.normal(170, 6, size=10000)
is_w_taller = (m_height < f_height).mean()
is_w_taller

0.2102

In [103]:
#6

def contains_a_1(issue):
    return 1 in issue.values
issue = np.random.choice(range(1,251), size=(10000,450))

(pd.DataFrame(issue).apply(contains_a_1, axis=1) == 0).mean()

0.1642

In [111]:
issue = np.random.choice(range(1,251), size=(10000,150))

1 - (pd.DataFrame(issue).apply(contains_a_1, axis=1) == 0).mean()

0.45840000000000003

In [110]:
#7

truck_there = np.random.choice(['There','Not There'], 
                                   p=(.7,.3), size=(10000,3))

(truck_there == 'Not There').all(axis=1).mean()

0.0273

In [114]:
truck_there = np.random.choice(['There','Not There'], 
                                   p=(.7,.3), size=(10000,4))

((truck_there == 'There').sum(axis=1) > 0).mean()

0.9922

In [116]:
#8

same_bday = np.random.choice(range(1,365), size=(10000,23))
same_bday 

array([[149, 211, 240, ..., 187, 264, 344],
       [ 52, 151, 347, ..., 287, 225, 146],
       [154,  82, 186, ..., 132,  16, 168],
       ...,
       [105,  91,  81, ...,  11, 282, 179],
       [224,  20, 179, ..., 333,  10, 188],
       [271, 275, 338, ..., 232, 190, 211]])