In [1]:
import numpy as np

In [5]:
rolls = np.random.choice(range(1,7),size=(1000,2))
rolls

array([[4, 4],
       [3, 5],
       [1, 4],
       ...,
       [4, 4],
       [1, 1],
       [4, 4]])

In [9]:
[rolls[i][0] == rolls[i][1] for i in rolls]

[array([ True,  True]),
 array([False,  True]),
 array([False, False]),
 array([False, False]),
 array([False, False]),
 array([False, False]),
 array([False, False]),
 array([False, False]),
 array([ True,  True]),
 array([False, False]),
 array([ True,  True]),
 array([False, False]),
 array([ True,  True]),
 array([False, False]),
 array([False, False]),
 array([False, False]),
 array([ True,  True]),
 array([ True,  True]),
 array([False, False]),
 array([False,  True]),
 array([False, False]),
 array([False, False]),
 array([False, False]),
 array([False, False]),
 array([False,  True]),
 array([False,  True]),
 array([False, False]),
 array([ True,  True]),
 array([False, False]),
 array([False, False]),
 array([False, False]),
 array([False, False]),
 array([False,  True]),
 array([ True,  True]),
 array([False, False]),
 array([False, False]),
 array([False, False]),
 array([False, False]),
 array([False, False]),
 array([False, False]),
 array([False, False]),
 array([False, F